# Generated by Django 2.1 on 2018-09-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarBrand')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_OCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klientName', models.CharField(max_length=100)),
                ('klientAdress', models.CharField(max_length=200)),
                ('objectBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarBrand')),
                ('objectModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarModel')),
            ],
        ),
    ]
