# Generated by Django 2.1 on 2018-09-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationOCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContractOCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klientName', models.CharField(max_length=70)),
                ('klientAdress', models.CharField(max_length=200)),
                ('objectRegNumber', models.CharField(max_length=10)),
                ('objectVIN', models.CharField(max_length=17)),
                ('contractBeginDate', models.DateTimeField()),
                ('contractEndDate', models.DateTimeField()),
                ('contractRegDate', models.DateTimeField(auto_now_add=True)),
                ('calc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ocv.CalculationOCV')),
                ('objectBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarBrand')),
                ('objectModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarModel')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlementName', models.CharField(max_length=50)),
                ('settlementRegion', models.CharField(max_length=50)),
                ('settlementMTSBUCodeBool', models.BooleanField()),
                ('settlementMTSBUCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract_ocv',
            name='objectBrand',
        ),
        migrations.RemoveField(
            model_name='contract_ocv',
            name='objectModel',
        ),
        migrations.DeleteModel(
            name='Contract_OCV',
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlementZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.Zone'),
        ),
        migrations.AddField(
            model_name='calculationocv',
            name='catTypeCalc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarType'),
        ),
        migrations.AddField(
            model_name='calculationocv',
            name='setlCalc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.Settlement'),
        ),
    ]
