# Generated by Django 2.1 on 2018-09-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocv', '0002_auto_20180918_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTypeLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carTypeLabel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarTypeMTSBU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carTypeKind', models.CharField(max_length=30)),
                ('carTypeMTSBU', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarTypeSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carTypeSimple', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuranceCompanyName', models.CharField(max_length=50)),
                ('insuranceCompanyLogo', models.ImageField(upload_to='imgs')),
                ('insuranceCompanyURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceOCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='calculationocv',
            name='catTypeCalc',
        ),
        migrations.RemoveField(
            model_name='calculationocv',
            name='price',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.AddField(
            model_name='priceocv',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CalculationOCV'),
        ),
        migrations.AddField(
            model_name='priceocv',
            name='insuranceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.InsuranceCompany'),
        ),
        migrations.AddField(
            model_name='cartypemtsbu',
            name='carTypeSimple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarTypeSimple'),
        ),
        migrations.AddField(
            model_name='cartypelabel',
            name='carTypeSimple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocv.CarTypeSimple'),
        ),
        migrations.AddField(
            model_name='calculationocv',
            name='carTypeLabelCalc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocv.CarTypeLabel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationocv',
            name='carTypeMTSBUCalc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocv.CarTypeMTSBU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculationocv',
            name='catTypeSimpleCalc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocv.CarTypeSimple'),
            preserve_default=False,
        ),
    ]
